// <auto-generated />
using System;
using Fortedle.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fortedle.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119144640_AddEmployeeWeeksTable")]
    partial class AddEmployeeWeeksTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fortedle.Server.Models.Database.EmployeeWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BillableHours")
                        .HasColumnType("double precision")
                        .HasColumnName("billable_hours");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision")
                        .HasColumnName("hours");

                    b.Property<bool>("IsLotteryEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lottery_eligible");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("week_end");

                    b.Property<string>("WeekKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("week_key");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_employee_weeks_user_id");

                    b.HasIndex("WeekKey")
                        .HasDatabaseName("idx_employee_weeks_week_key");

                    b.HasIndex("WeekStart")
                        .HasDatabaseName("idx_employee_weeks_week_start");

                    b.HasIndex("UserId", "WeekKey")
                        .IsUnique()
                        .HasDatabaseName("idx_employee_weeks_user_week");

                    b.ToTable("employee_weeks");
                });
#pragma warning restore 612, 618
        }
    }
}
